version: 0.1
downloads:
  - name: php-cli
    downloads:
      - os:
          linux: linux
          macos: macos
        cpu:
          x86_64: x86_64
          arm_64: arm64
        url: https://github.com/matthewbaggett/packaged-tooling/releases/download/${version}/php-8.2-${os}-${cpu}
tools:
  definitions:
    - name: php
      download: php-cli
      known_good_version: 0.0.1
      environment:
        - name: PATH
          list: ["${tool}/bin"]
      shims:
        - name: php
          target: php-cli