version: 0.1
actions:
  definitions:
    - id: php-automatic-composer-install-on-change
      description: "Composer Install when composer.json or composer.lock change"
      triggers:
        - files: [composer.json, composer.lock]
      run: composer install ${target}

    - id: php-automatic-composer-install-on-update
      description: "Composer Install when updating from git"
      triggers:
        - git_hooks: [post-checkout, post-merge]
      run: composer install ${target}

    - id: php-automatic-composer-update-daily
      description: "Composer Update Daily"
      triggers:
        - schedule: 24h
      run: composer update ${target}

    - id: php-automatic-php-cs-fixer
      description: "Automatically run PHP-CS-Fixer when files change"
      triggers:
        - files: ["**.php"]
      run: php-cs-fixer fix ${target}
